version: 0.2

phases:
  install:
    runtime-versions:
        docker: 18
  build:
    commands:
       - echo Build started on `date`
       - npm install
       - $(aws ecr get-login --region us-east-2 --no-include-email)
       - docker build -t 102239939291.dkr.ecr.us-east-2.amazonaws.com/octank/credit-api:0.0.1 .
       - docker push 102239939291.dkr.ecr.us-east-2.amazonaws.com/octank/credit-api:0.0.1
artifacts:
  files:
    - imagedefinitions.json
