apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mortgage-api-chart.fullname" . }}
  labels:
    {{- include "mortgage-api-chart.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "mortgage-api-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "mortgage-api-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mortgage-api-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AURORA_DB_MORTGAGE
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: aurora.db.mortgage
            - name: AURORA_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: aurora-config
                  key: aurora.db.service
            - name: AURORA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: aurora-security
                  key: db.user.name
            - name: AURORA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aurora-security
                  key: db.user.password
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /rates
              port: http
          readinessProbe:
            httpGet:
              path: /rates
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
