/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:333fb3aa-8e1c-44b2-9bc6-c4c87057e510",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_hX3Phm62E",
    "aws_user_pools_web_client_id": "6s8deq3i3q3a782nv6vk49ainh",
    "oauth": {}
};


export default awsmobile;
